flairs = {
    'team-gb': 'Team GB 2012',
    'misc-1966-england': 'World Cup - England \'66',
    'eng-everton': 'Everton',
    'eurnat-united-kingdom': 'United Kingdom',
    'esp-mallorca': 'Mallorca',
    'usa-houston': 'Houston',
    'fed-spain': 'Spain',
    'ita-juventus': 'Juventus',
    'sco-dundee-united': 'Dundee Utd',
    'germ-vfb-stuttgart': 'VfB Stuttgart',
    'fr-paris-saint-germain': 'Paris St. Germain',
    'ire-shamrock-rovers': 'Shamrock Rovers',
    'neth-feyenoord': 'Feyenoord',
    'tur-galatasaray': 'Galatasaray',
    'oz-perth-glory': 'Perth Glory',
    'bra-sao-paulo': 'Sao Paulo',
    'gre-panathinaikos': 'Panathinaikos',
    'arg-river-plate': 'River Plate',
    'bel-anderlecht': 'Anderlecht',
    'den-brondby': 'Brondby',
    'ni-glentoran': 'Glentoran',
    'rus-cska-moscow': 'CSKA Moscow',
    'jap-yokohama-f-marinos': 'Yokohama F Marinos',
    'swe-malmo': 'Malmo',
    'conmebol-brazil': 'Brazil',
    'euro-mascot-1992': 'Sweden \'92 (Rabbit)'
}
